#install: travis_wait mvn install

sudo: required
services:
  - docker

before_install:
  - docker build -t hikaritanabe/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true hikaritanabe/react-test npm test

after_success:
  - docker build -t hikaritanabe/multi-client ./client
  - docker build -t hikaritanabe/multi-nginx ./nginx
  - docker build -t hikaritanabe/multi-server ./server
  - docker build -t hikaritanabe/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  # Thake those images and push them to docker hub
  - docker push hikaritanabe/multi-client
  - docker push hikaritanabe/multi-nginx
  - docker push hikaritanabe/multi-server
  - docker push hikaritanabe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-085107194442'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
